version = 1

exclude_patterns = [
  "vendor/**",
  "module/agent/**",
  "module/player/**",
  "module/gateway/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/wenchangshou/vd-node-manage"