// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: rpc-old/server/pb/resource.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResourceDetailedInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string                                `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name     string                                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category string                                `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	File     *GetResourceDetailedInfoResponse_File `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *GetResourceDetailedInfoResponse) Reset() {
	*x = GetResourceDetailedInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_pb_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResourceDetailedInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceDetailedInfoResponse) ProtoMessage() {}

func (x *GetResourceDetailedInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_pb_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceDetailedInfoResponse.ProtoReflect.Descriptor instead.
func (*GetResourceDetailedInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_server_pb_resource_proto_rawDescGZIP(), []int{0}
}

func (x *GetResourceDetailedInfoResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetResourceDetailedInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetResourceDetailedInfoResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetResourceDetailedInfoResponse) GetFile() *GetResourceDetailedInfoResponse_File {
	if x != nil {
		return x.File
	}
	return nil
}

type GetResourceDetailedInfoResponse_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size       int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Url        string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	SourceName string `protobuf:"bytes,5,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	Uuid       string `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *GetResourceDetailedInfoResponse_File) Reset() {
	*x = GetResourceDetailedInfoResponse_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_pb_resource_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResourceDetailedInfoResponse_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceDetailedInfoResponse_File) ProtoMessage() {}

func (x *GetResourceDetailedInfoResponse_File) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_pb_resource_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceDetailedInfoResponse_File.ProtoReflect.Descriptor instead.
func (*GetResourceDetailedInfoResponse_File) Descriptor() ([]byte, []int) {
	return file_rpc_server_pb_resource_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetResourceDetailedInfoResponse_File) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetResourceDetailedInfoResponse_File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetResourceDetailedInfoResponse_File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetResourceDetailedInfoResponse_File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetResourceDetailedInfoResponse_File) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *GetResourceDetailedInfoResponse_File) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_rpc_server_pb_resource_proto protoreflect.FileDescriptor

var file_rpc_server_pb_resource_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3,
	0x02, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x39, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0x84, 0x01,
	0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x32, 0x6f, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x59, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x1a, 0x20, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x73, 0x68, 0x6f, 0x75,
	0x32, 0x2f, 0x76, 0x64, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_server_pb_resource_proto_rawDescOnce sync.Once
	file_rpc_server_pb_resource_proto_rawDescData = file_rpc_server_pb_resource_proto_rawDesc
)

func file_rpc_server_pb_resource_proto_rawDescGZIP() []byte {
	file_rpc_server_pb_resource_proto_rawDescOnce.Do(func() {
		file_rpc_server_pb_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_server_pb_resource_proto_rawDescData)
	})
	return file_rpc_server_pb_resource_proto_rawDescData
}

var file_rpc_server_pb_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_server_pb_resource_proto_goTypes = []interface{}{
	(*GetResourceDetailedInfoResponse)(nil),      // 0: GetResourceDetailedInfoResponse
	(*GetResourceDetailedInfoResponse_File)(nil), // 1: GetResourceDetailedInfoResponse.File
	(*wrapperspb.StringValue)(nil),               // 2: google.protobuf.StringValue
}
var file_rpc_server_pb_resource_proto_depIdxs = []int32{
	1, // 0: GetResourceDetailedInfoResponse.file:type_name -> GetResourceDetailedInfoResponse.File
	2, // 1: ResourceManagement.GetResourceDetailedInfo:input_type -> google.protobuf.StringValue
	0, // 2: ResourceManagement.GetResourceDetailedInfo:output_type -> GetResourceDetailedInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_server_pb_resource_proto_init() }
func file_rpc_server_pb_resource_proto_init() {
	if File_rpc_server_pb_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_server_pb_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResourceDetailedInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_server_pb_resource_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResourceDetailedInfoResponse_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_server_pb_resource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_server_pb_resource_proto_goTypes,
		DependencyIndexes: file_rpc_server_pb_resource_proto_depIdxs,
		MessageInfos:      file_rpc_server_pb_resource_proto_msgTypes,
	}.Build()
	File_rpc_server_pb_resource_proto = out.File
	file_rpc_server_pb_resource_proto_rawDesc = nil
	file_rpc_server_pb_resource_proto_goTypes = nil
	file_rpc_server_pb_resource_proto_depIdxs = nil
}
